version: "2"
linters:
  enable:
    - revive
    - unparam
  settings:
    revive:
      rules:
        - name: empty-block
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        text: QF1003 # https://staticcheck.dev/docs/checks#QF1003
    paths:
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
