version: 2

before:
  hooks:
  - go mod tidy

builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  ignore:
  # We don't want to publish a linux-arm64 binary
  - goos: linux
    goarch: arm64
  ldflags:
  - -X github.com/bitrise-io/bitrise/v2/version.VERSION={{ .Version }}
  - -X github.com/bitrise-io/bitrise/v2/version.Commit={{ .FullCommit }}
  - -X github.com/bitrise-io/bitrise/v2/version.BuildNumber={{ index .Env "BITRISE_BUILD_NUMBER" }}

archives:
  # GitHub release should contain the raw binaries (no zip or tar.gz)
- format: binary
  id: default
  # Name format should match the curl install script
  name_template: >-
    {{ .ProjectName }}-
    {{- title .Os }}-
    {{- if eq .Arch "amd64" }}x86_64
    {{- else }}{{ .Arch }}{{ end }}

- format: binary
  id: s3
  name_template: "{{ .ProjectName }}-cli-{{ .Os }}-{{ .Arch }}-v{{ .Version }}"

blobs:
- provider: gs
  bucket: bitrise-cli-releases-prod
  directory: /{{ .Version }}
  ids:
  - default
- provider: s3
  bucket: bitrise-cli-releases-prod
  region: us-east-1
  endpoint: "{{ .Env.AWS_ENDPOINT_URL }}"
  directory: /
  ids:
  - s3

release:
  github:
    owner: bitrise-io
    name: bitrise
  ids:
  - default
  draft: true
  mode: replace
  name_template: "{{ .Version }}"
  footer: |
    ### Install instructions

    <a href="https://repology.org/project/bitrise/versions">
      <img src="https://repology.org/badge/vertical-allrepos/bitrise.svg" alt="Packaging status" align="right">
    </a>

    There are multiple way to install Bitrise CLI:

    - Homebrew: `brew install bitrise`
    - Nix: available as `bitrise` [in nixpkgs](https://search.nixos.org/packages?channel=unstable&show=bitrise), run `nix-shell -p bitrise` or your preferred configuration method.
    - Download a pre-built binary below
    - There might be other [community-maintained packages](https://repology.org/project/bitrise/versions)

    You can enable shell completion for the `bitrise run` command: [https://blog.bitrise.io/workflow-id-completion](https://blog.bitrise.io/workflow-id-completion)

    #### Building from source

    Set up the right Go version indicated by the `go.mod` file, then run `go install .`

checksum:
  name_template: checksums.txt
snapshot:
  # Run `goreleaser release --snapshot` locally to create binaries without publishing and checks
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - "^docs:"
    - "'^test:"
