---
format_version: "17"
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: other

app:
  status_report_name: Run <target_id> pipeline

pipelines:
  ci:
    triggers:
      push:
      - branch: master
      pull_request:
      - source_branch: "*"
    workflows:
      run_lint: {}
      run_unit_tests_macos: {}
      run_unit_tests_linux: {}
      run_integration_tests_macos: {}
      run_integration_tests_linux: {}
      run_docker_integration_tests_linux: {}
      test_binary_build_macos: {}
      test_binary_build_linux: {}

workflows:
  release:
    triggers:
      tag:
      - name: "*.*.*"
    steps:
    - trigger-bitrise-workflow@0:
        inputs:
        - api_token: $CONTROL_CENTER_TRIGGER_KEY
        - workflow_id: binary-tool-release
        - exported_environment_variable_names: GIT_REPOSITORY_URL
        - app_slug: $CONTROL_CENTER_APP_SLUG

  run_lint:
    steps:
    - bundle::setup_repo: {}
    - bundle::install_dependencies: {}
    - bundle::run_lint: {}

  run_unit_tests_macos:
    steps:
    - bundle::setup_repo: {}
    - bundle::install_dependencies: {}
    - bundle::setup_go_junit_report: {}
    - bundle::run_unit_tests: {}
    meta:
      bitrise.io:
        stack: osx-xcode-16.4.x
        machine_type_id: g2.mac.large

  run_unit_tests_linux:
    steps:
    - bundle::setup_repo: {}
    - bundle::install_dependencies:
        inputs:
        - IGNORE_CUSTOM_GOLANG: "true"
    - bundle::setup_go_junit_report: {}
    - bundle::run_unit_tests: {}

  run_integration_tests_macos:
    steps:
    - bundle::setup_repo: {}
    - bundle::install_dependencies: {}
    - bundle::setup_go_junit_report: {}
    - bundle::run_integration_tests: {}
    meta:
      bitrise.io:
        # TODO: switch to stable stack when Nix is rolled out there
        stack: osx-xcode-edge
        machine_type_id: g2.mac.large

  run_integration_tests_linux:
    steps:
    - bundle::setup_repo: {}
    - bundle::install_dependencies:
        inputs:
        - IGNORE_CUSTOM_GOLANG: "true"
    - bundle::setup_go_junit_report: {}
    - bundle::run_integration_tests: {}
    meta:
      bitrise.io:
        # TODO: switch to stable stack when Nix is rolled out there
        stack: ubuntu-noble-24.04-bitrise-2025-android
        machine_type_id: g2.linux.x-large

  run_docker_integration_tests_linux:
    steps:
    - bundle::setup_repo: {}
    - bundle::install_dependencies:
        inputs:
        - IGNORE_CUSTOM_GOLANG: "true"
    - bundle::setup_go_junit_report: {}
    - bundle::run_docker_integration_tests:
        envs:
        - SRC_DIR_IN_GOPATH: $BITRISE_SOURCE_DIR

  # Note: this workflow is triggered externally during stack testing, do not remove or break.
  run_system_asdf_tests:
    steps:
    - bundle::setup_repo: {}
    - bundle::install_dependencies: {}
    - bundle::setup_go_junit_report: {}
    - bundle::run_system_asdf_integration_tests: {}

  # Note: this workflow is triggered externally during stack testing, do not remove or break.
  run_system_mise_tests:
    steps:
    - bundle::setup_repo: {}
    - bundle::install_dependencies: {}
    - bundle::setup_go_junit_report: {}
    - bundle::run_system_mise_integration_tests: {}

  test_binary_build_macos:
    steps:
    - bundle::setup_repo: {}
    - bundle::install_dependencies: {}
    - bundle::setup_goreleaser: {}
    - bundle::test_binary_build: {}
    meta:
      bitrise.io:
        stack: osx-xcode-16.4.x
        machine_type_id: g2.mac.large

  test_binary_build_linux:
    steps:
    - bundle::setup_repo: {}
    - bundle::install_dependencies:
        inputs:
        - IGNORE_CUSTOM_GOLANG: "true"
    - bundle::setup_goreleaser: {}
    - bundle::test_binary_build: {}

  create-release:
    description: Creates Linux and Darwin binaries, then publishes a GitHub release
    envs:
    - GITHUB_TOKEN: $GIT_BOT_USER_ACCESS_TOKEN # Goreleaser expects this env var
    # R2 bucket connection params
    - AWS_ENDPOINT_URL: $AWS_ENDPOINT_PROD
    - AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID_PROD
    - AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_PROD
    steps:
    - script@1:
        title: Validate if Bitrise CLI version matches the git tag
        inputs:
        - content: |-
            #!/bin/bash
            set -ex

            version=$(go run main.go --version)
            if [[ "v$version" != "$BITRISE_GIT_TAG" ]]; then
              echo "Bitrise CLI version ($version) does not match the git tag ($BITRISE_GIT_TAG)"
              echo "Please update the Bitrise CLI version to match the git tag"
              exit 1
            fi
    - script@1:
        title: Fetch GCS bucket credentials
        inputs:
        - content: |-
            #!/bin/bash
            set -ex

            echo "$GCS_BITRISE_CLI_BUCKET_CREDENTIALS" > /tmp/gcs_service_account.json
            # Goreleaser expects this env var:
            envman add --key GOOGLE_APPLICATION_CREDENTIALS --value /tmp/gcs_service_account.json
    - script@1:
        title: Goreleaser (create binaries + publish to GH)
        deps:
          brew:
          - name: goreleaser
        inputs:
        - content: |
            #!/usr/bin/env bash
            set -ex

            goreleaser release

  noop:
    title: Noop
    description: Empty workflow for quick testing

  fail-test:
    title: Fails
    description: Workflow will fail
    steps:
    - script:
        title: Success
        inputs:
        - content: |-
            set -ex
            exit 0
    - script:
        title: Fail wit exit code 2
        inputs:
        - content: |-
            set -ex
            exit 2
    - script:
        title: Skippable fail with exit code 2
        is_always_run: true
        is_skippable: true
        inputs:
        - content: |-
            set -ex
            exit 2
    - script:
        title: Skipping success
        is_always_run: false
        inputs:
        - content: |-
            set -ex
            exit 0

  unpin-go-version:
    title: Unpin Go version from .tool-versions
    description: |-
      Removes golang line from .tool-versions file, so the global version is used.
      TODO: this is only needed as long as Go steps are built from source
      (because tool setup has no influence on the environment of the CLI process itself, just the environment of the workflow).
    steps:
    - script@1:
        title: Unpin Go version
        inputs:
        - content: |-
            #!/bin/bash
            set -ex

            TOOL_VERSIONS_FILE=".tool-versions"

            if [ ! -f "$TOOL_VERSIONS_FILE" ]; then
                echo "Error: $TOOL_VERSIONS_FILE not found"
                exit 1
            fi

            # Remove lines with golang from .tool-versions
            grep -v '^golang ' "$TOOL_VERSIONS_FILE" > "$TOOL_VERSIONS_FILE.tmp" || true
            mv "$TOOL_VERSIONS_FILE.tmp" "$TOOL_VERSIONS_FILE"

step_bundles:
  run_lint:
    title: Run linter
    steps:
    - script:
        title: golangci-lint
        inputs:
        - content: |-
            #!/usr/bin/env bash
            set -ex
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s v2.6.0
            ./bin/golangci-lint run

  run_unit_tests:
    steps:
    - script@1:
        title: Run unit tests
        inputs:
        - content: |-
            #!/usr/bin/env bash
            set -exo pipefail

            # Here we save the original test results and deploy directories and later on we recreate them,
            #  because during the tests these directories are removed.
            ORIG_BITRISE_TEST_RESULT_DIR="${BITRISE_TEST_RESULT_DIR}"
            ORIG_BITRISE_DEPLOY_DIR="${BITRISE_DEPLOY_DIR}"

            # Setup per OS test name and log file name
            if [ "$(uname)" = "Linux" ]; then
              test_name_json='{"test-name":"Unit tests on Linux"}'
              test_log_file_name="unit_tests_linux"
            else
              test_name_json='{"test-name":"Unit tests on macOS"}'
              test_log_file_name="unit_tests_macos"
            fi

            # Run tests and generate report
            go test -v -p 1 ./... 2>&1 | tee "./${test_log_file_name}.log"
            mkdir -p "${ORIG_BITRISE_DEPLOY_DIR}"
            cp "./${test_log_file_name}.log" "${ORIG_BITRISE_DEPLOY_DIR}/${test_log_file_name}.log"
            go-junit-report -in "./${test_log_file_name}.log" -out "${ORIG_BITRISE_DEPLOY_DIR}/${test_log_file_name}.xml"

            # Export the junit test results
            test_results_dir="${ORIG_BITRISE_TEST_RESULT_DIR}/unit_test_results"
            mkdir -p "${test_results_dir}"
            cp "${ORIG_BITRISE_DEPLOY_DIR}/${test_log_file_name}.xml" "${test_results_dir}/${test_log_file_name}.xml"
            echo "${test_name_json}" > "${test_results_dir}/test-info.json"
    - deploy-to-bitrise-io@2: {}

  run_integration_tests:
    steps:
    - script@1:
        title: Run integration tests
        inputs:
        - content: |-
            #!/usr/bin/env bash
            set -exo pipefail

            export BITRISE_ANALYTICS_DISABLED=true

            # Here we save the original test results and deploy directories and later on we recreate them,
            #  because during the tests these directories are removed.
            ORIG_BITRISE_TEST_RESULT_DIR="${BITRISE_TEST_RESULT_DIR}"
            ORIG_BITRISE_DEPLOY_DIR="${BITRISE_DEPLOY_DIR}"

            # Build and setup the current binary
            current_bitrise="$(pwd)/_tmp/test_bitrise"
            export CGO_ENABLED=0
            go build -o "$current_bitrise"

            export PR="" PULL_REQUEST_ID=""
            export INTEGRATION_TEST_BINARY_PATH="$current_bitrise"
            $current_bitrise setup

            # Setup per OS test name and log file name
            if [ "$(uname)" = "Linux" ]; then
              test_name_json='{"test-name":"Integration tests on Linux"}'
              test_log_file_name="integration_tests_linux"
            else
              test_name_json='{"test-name":"Integration tests on macOS"}'
              test_log_file_name="integration_tests_macos"
            fi

            # Run tests and generate report
            set +e  # Temporarily disable exit on error
            # Note about `-p 1`: `bitrise run` is not parallelizable and has some race conditions, we need to execute tests sequentially
            cd ./integrationtests && go test -v --tags linux_and_mac -p 1 ./... 2>&1 | tee "./${test_log_file_name}.log"
            test_exit_code=$?
            set -e  # Re-enable exit on error

            mkdir -p "${ORIG_BITRISE_DEPLOY_DIR}"
            cp "./${test_log_file_name}.log" "${ORIG_BITRISE_DEPLOY_DIR}/${test_log_file_name}.log"

            go-junit-report -in "./${test_log_file_name}.log" -out "${ORIG_BITRISE_DEPLOY_DIR}/${test_log_file_name}.xml"

            # Export the junit test results
            test_results_dir="${ORIG_BITRISE_TEST_RESULT_DIR}/integration_test_results"
            mkdir -p "${test_results_dir}"
            cp "${ORIG_BITRISE_DEPLOY_DIR}/${test_log_file_name}.xml" "${test_results_dir}/${test_log_file_name}.xml"
            echo "${test_name_json}" > "${test_results_dir}/test-info.json"

            exit $test_exit_code
    - deploy-to-bitrise-io@2: {}

  run_system_asdf_integration_tests:
    steps:
    - script@1:
        title: Run integration tests against system asdf
        inputs:
        - content: |
            #!/bin/bash
            set -ex

            # Special test mode that doesn't use the test harness but uses the system-wide asdf install and config
            export TOOLPROVIDER_TEST_USE_SYSTEM_ASDF=1
            # We test the system bitrise executable, not one built from source
            export INTEGRATION_TEST_BINARY_PATH="$(which bitrise)"
            cd integrationtests && go test -v --tags linux_and_mac ./toolprovider/asdf/... -timeout 360s

  run_system_mise_integration_tests:
    steps:
    - script@1:
        title: Run mise integration tests against system
        inputs:
        - content: |
            #!/bin/bash
            set -ex

            # We test the system bitrise executable, not one built from source
            export INTEGRATION_TEST_BINARY_PATH="$(which bitrise)"
            cd integrationtests && go test -v --tags linux_and_mac ./toolprovider/mise/... -timeout 360s

  run_docker_integration_tests:
    steps:
    - script@1:
        title: Docker login for pulls
        run_if: .IsCI
        inputs:
          - content: echo "${DOCKER_LOGIN_PULLONLY_PASS}" | docker login -u bitrisedev --password-stdin
    - script@1:
        title: Run integration tests
        inputs:
        - content: |-
            #!/usr/bin/env bash
            set -exo pipefail

            # Here we save the original test results and deploy directories and later on we recreate them,
            #  because during the tests these directories are removed.
            ORIG_BITRISE_TEST_RESULT_DIR="${BITRISE_TEST_RESULT_DIR}"
            ORIG_BITRISE_DEPLOY_DIR="${BITRISE_DEPLOY_DIR}"

            # Build and setup the current binary
            current_bitrise="$(pwd)/_tmp/test_bitrise"
            export CGO_ENABLED=0
            go build -o "$current_bitrise"

            export PR="" PULL_REQUEST_ID=""
            export INTEGRATION_TEST_BINARY_PATH="$current_bitrise"
            $current_bitrise setup

            # Setup per OS test name and log file name
            linux_only_test_name_json='{"test-name":"Linux only integration tests"}'
            linux_only_test_log_file_name="linux_only_integration_tests"

            # Run tests and generate report
            set +e  # Temporarily disable exit on error
            cd ./integrationtests && go test -v -p 1 --tags linux_only ./... 2>&1 | tee "./${linux_only_test_log_file_name}.log"
            test_exit_code=$?
            set -e  # Re-enable exit on error

            mkdir -p "${ORIG_BITRISE_DEPLOY_DIR}"
            cp "./${linux_only_test_log_file_name}.log" "${ORIG_BITRISE_DEPLOY_DIR}/${linux_only_test_log_file_name}.log"

            go-junit-report -in "./${linux_only_test_log_file_name}.log" -out "${ORIG_BITRISE_DEPLOY_DIR}/${linux_only_test_log_file_name}.xml"

            # Export the junit test results
            test_results_dir="${ORIG_BITRISE_TEST_RESULT_DIR}/linux_only_integration_test_results"
            mkdir -p "${test_results_dir}"
            cp "${ORIG_BITRISE_DEPLOY_DIR}/${linux_only_test_log_file_name}.xml" "${test_results_dir}/${linux_only_test_log_file_name}.xml"
            echo "${linux_only_test_name_json}" > "${test_results_dir}/test-info.json"

            # Exit with the original test exit code
            exit $test_exit_code
    - deploy-to-bitrise-io@2: {}

  test_binary_build:
    steps:
    - script@1:
        title: Create snapshot binaries
        deps:
          brew:
          - name: goreleaser
        inputs:
        - content: |
            #!/usr/bin/env bash
            set -ex

            goreleaser release --snapshot --clean
    - deploy-to-bitrise-io@2: {}

  setup_repo:
    steps:
    - git-clone@8:
        inputs:
        - fetch_tags: "yes"

  setup_go_junit_report:
    steps:
    - script@1:
        title: Setup JUnit XML converter
        inputs:
        - content: |-
            #!/usr/bin/env bash
            set -ex
            go install github.com/jstemmer/go-junit-report/v2@latest
            asdf reshim golang

  setup_goreleaser:
    steps:
    - script@1:
        inputs:
        - content: |-
            #!/bin/bash
            set -ex
            go install github.com/goreleaser/goreleaser/v2@latest
            asdf reshim golang

  install_dependencies:
    steps:
    - bitrise-run@0:
        inputs:
        - workflow_id: unpin-go-version
        run_if: '{{ enveq "IGNORE_CUSTOM_GOLANG" "true" }}'
    - script@1:
        inputs:
        - content: >-
            #!/usr/bin/env bash

            # fail if any commands fails

            set -e

            # make pipelines' return status equal the last command to exit with
            a non-zero status, or zero if all commands exit successfully

            set -o pipefail

            # debug log

            set -x


            bitrise tools setup --config .tool-versions
    - script@1:
        inputs:
        - content: >-
            #!/usr/bin/env bash

            # fail if any commands fails

            set -e

            # make pipelines' return status equal the last command to exit with
            a non-zero status, or zero if all commands exit successfully

            set -o pipefail

            # debug log

            set -x


            go version
        title: Check go version
    inputs:
    - IGNORE_CUSTOM_GOLANG: "false"
      opts:
        title: Skip Custom Golang Version Installation
        value_options:
        - "true"
        - "false"
        description: >-
          Removes golang line from .tool-versions file, so the global version is
          used.

          TODO: this is only needed as long as Go steps are built from source

          (because tool setup has no influence on the environment of the CLI
          process itself, just the environment of the workflow).

meta:
  bitrise.io:
    machine_type_id: g2.linux.x-large
    stack: ubuntu-noble-24.04-bitrise-2025-android
