services:
  main-container:
    build:
      context: .
    platform: linux/amd64
    volumes:
      - /tmp:/tmp
      - ../_containers/.bitrise:/root/.bitrise
      - ./:/usr/src/bitrise
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /usr/src/bitrise
    command: sleep infinity
