package bitrise

const (
	// CIModeEnvKey ...
	CIModeEnvKey string = "CI"
	// PullRequestIDEnvKey ...
	PullRequestIDEnvKey string = "PULL_REQUEST_ID"
	// DebugModeEnvKey ...
	DebugModeEnvKey string = "DEBUG"
	// LogLevelEnvKey ...
	LogLevelEnvKey string = "LOGLEVEL"
)
