package bitrise

const (
	// CIModeEnvKey ...
	CIModeEnvKey string = "CI"
	// PRModeEnvKey ...
	PRModeEnvKey string = "PR"
	// PullRequestIDEnvKey ...
	PullRequestIDEnvKey string = "PULL_REQUEST_ID"
	// DebugModeEnvKey ...
	DebugModeEnvKey string = "DEBUG"
	// LogLevelEnvKey ...
	LogLevelEnvKey string = "LOGLEVEL"
	// OptOutAnalytics ...
	OptOutAnalytics string = "OPT_OUT_ANALYTICS"
)
