format_version: 1.3.0
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git

trigger_map:
- pattern: deprecated_pr_allowed
  is_pull_request_allowed: true
  workflow: deprecated_pr_allowed
- pattern: deprecated_only_code_push
  is_pull_request_allowed: false
  workflow: deprecated_only_code_push
- push_branch: code-push
  workflow: code-push
- pull_request_source_branch: pull_request_source_branch
  workflow: pull_request
- pull_request_target_branch: pull_request_taget_branch
  workflow: pull_request
- tag: tag
  workflow: tag
- pattern: deprecated_pipeline_trigger
  is_pull_request_allowed: false
  pipeline: deprecated_pipeline
- push_branch: pipeline_trigger
  pipeline: code_push_pipeline

pipelines:
  deprecated_pipeline:
    stages:
    - deprecated_stage: { }
  code_push_pipeline:
    stages:
    - code_push_stage: { }

stages:
  deprecated_stage:
    workflows:
    - deprecated_pr_allowed: { }
  code_push_stage:
    workflows:
    - code-push: { }

workflows:
  # PR tests
  deprecated_pr_allowed:
  deprecated_only_code_push:
  code-push:
  pull_request:
  tag:
