step_bundles:
  print:
    steps:
    - script@1.2.1:
        inputs:
        - content: echo "Hello $NAME!"

workflows:
  print_hello_world:
    envs:
    - NAME: World
    steps:
    - bundle::print: { }
