// Command gendocs renders the bitrise command tree into a markdown
// reference, one file per command, under docs/cli, and refreshes the
// command overview embedded in README.md.
//
// Run it via `make docs`. The output is committed, so every change to a
// command, flag, or help text shows up as a reviewable diff in the PR that
// makes it; `make docs-check` (run in CI) fails when the committed files
// drift from the command definitions.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"

	"github.com/bitrise-io/bitrise/v2/cli"
)

const (
	outDir     = "docs/cli"
	readmePath = "README.md"

	// The overview is injected between these markers in README.md.
	beginMarker = "<!-- commands-overview:begin — generated by `make docs`; do not edit by hand -->"
	endMarker   = "<!-- commands-overview:end -->"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "gendocs:", err)
		os.Exit(1)
	}
}

func run() error {
	root := cli.NewRootCommandForDocs()
	// The default footer stamps the generation date into every file, which
	// would dirty the tree on each regeneration; git history already records
	// when the docs changed.
	root.DisableAutoGenTag = true

	if err := os.MkdirAll(outDir, 0o750); err != nil {
		return err
	}
	// Remove previously generated files so commands deleted from the tree
	// don't leave stale pages behind.
	entries, err := os.ReadDir(outDir)
	if err != nil {
		return err
	}
	for _, e := range entries {
		if !e.IsDir() && strings.HasPrefix(e.Name(), "bitrise") && strings.HasSuffix(e.Name(), ".md") {
			if err := os.Remove(filepath.Join(outDir, e.Name())); err != nil {
				return err
			}
		}
	}
	if err := doc.GenMarkdownTree(root, outDir); err != nil {
		return err
	}
	return updateReadme(root)
}

// updateReadme replaces the section between beginMarker and endMarker in
// README.md with a freshly rendered command overview.
func updateReadme(root *cobra.Command) error {
	data, err := os.ReadFile(readmePath)
	if err != nil {
		return err
	}
	s := string(data)
	begin := strings.Index(s, beginMarker)
	end := strings.Index(s, endMarker)
	if begin == -1 || end == -1 || end < begin {
		return fmt.Errorf("%s: overview markers missing or out of order (expected %q before %q)", readmePath, beginMarker, endMarker)
	}
	updated := s[:begin+len(beginMarker)] + "\n\n" + renderOverview(root) + "\n\n" + s[end:]
	if updated == s {
		return nil
	}
	return os.WriteFile(readmePath, []byte(updated), 0o600)
}

// renderOverview renders one section per top-level command group (a table of
// its leaf commands, each linked to its docs/cli page), followed by a single
// table collecting top-level commands that have no subcommands.
func renderOverview(root *cobra.Command) string {
	var b strings.Builder
	var standalone []*cobra.Command
	for _, c := range root.Commands() {
		if !c.IsAvailableCommand() || c.IsAdditionalHelpTopicCommand() {
			continue
		}
		if !c.HasAvailableSubCommands() {
			standalone = append(standalone, c)
			continue
		}
		fmt.Fprintf(&b, "### [`%s`](%s) — %s\n\n", c.Name(), docPath(c), c.Short)
		b.WriteString("| Command | Description |\n|---|---|\n")
		writeLeafRows(&b, c)
		b.WriteString("\n")
	}
	if len(standalone) > 0 {
		b.WriteString("### Other commands\n\n| Command | Description |\n|---|---|\n")
		for _, c := range standalone {
			writeRow(&b, c)
		}
		b.WriteString("\n")
	}
	return strings.TrimRight(b.String(), "\n")
}

// writeLeafRows emits a table row for every leaf command under c,
// recursing through intermediate groups (e.g. rde → session → create).
func writeLeafRows(b *strings.Builder, c *cobra.Command) {
	for _, sub := range c.Commands() {
		if !sub.IsAvailableCommand() || sub.IsAdditionalHelpTopicCommand() {
			continue
		}
		if sub.HasAvailableSubCommands() {
			writeLeafRows(b, sub)
			continue
		}
		writeRow(b, sub)
	}
}

func writeRow(b *strings.Builder, c *cobra.Command) {
	path := strings.TrimPrefix(c.CommandPath(), c.Root().Name()+" ")
	fmt.Fprintf(b, "| [`%s`](%s) | %s |\n", path, docPath(c), c.Short)
}

// docPath returns the repo-relative path of the page GenMarkdownTree
// generates for c (command path with spaces replaced by underscores).
func docPath(c *cobra.Command) string {
	return outDir + "/" + strings.ReplaceAll(c.CommandPath(), " ", "_") + ".md"
}
