format_version: 1.3.0
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
containers:
  success:
    image: frolvlad/alpine-bash:latest
  fails-404:
    image: localhost.hu/noimage:3cb48a46a66e
  login-fail:
    image: us-central1-docker.pkg.dev/ip-kubernetes-dev/sandbox/ruby:zstd
    credentials:
      username: _json_key_base64
      password: bad pw
  login-success:
    image: localhost:5001/frolvlad/alpine-bash:latest
    credentials:
      username: test
      password: $DOCKER_PW
workflows:
  docker-pull-success:
    title: Expected to pass docker pull
    steps:
    - with:
        container: success
        steps:
        - script:
            title: Should pass
            inputs:
            - content: exit 0
  docker-pull-fails-404:
    title: Expected to fail docker pull
    steps:
    - with:
        container: fails-404
        steps:
        - script:
            title: Should fail
            inputs:
            - content: exit 0
  docker-login-fail:
    title: Expected to fail on docker login
    steps:
    - with:
        container: login-fail
        steps:
        - script:
            title: Should fail
            inputs:
            - content: exit 0
  docker-login-success:
    before_run:
    - _start_mock_registry
    after_run:
    - _cleanup_mock_registry
    title: Expected to pass docker login
    steps:
    - with:
        container: login-success
        steps:
        - script:
            title: Should pass
            inputs:
            - content: exit 0
  _start_mock_registry:
    steps:
    - script:
        title: setup mock registry
        inputs:
        - content: |-
            docker pull --platform linux/amd64 registry:latest
            docker run -d -p 5001:5000 --restart always --name registry registry
            docker pull --platform linux/amd64 frolvlad/alpine-bash:latest
            docker login localhost:5001 -u test -p test
            docker tag frolvlad/alpine-bash:latest localhost:5001/frolvlad/alpine-bash:latest
            docker push localhost:5001/frolvlad/alpine-bash:latest
            docker logout localhost:5001
  _cleanup_mock_registry:
    steps:
    - script:
        is_always_run: true
        title: cleanup mock registry
        inputs:
        - content: |-
            docker stop registry
            docker rm registry
