format_version: 1.3.0
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
containers:
  step_execution_container:
    image: localhost:5001/healthy-image
    credentials:
      username: $DOCKER_USR_STEP_EXECUTION_CONTAINER
      password: $DOCKER_PW_STEP_EXECUTION_CONTAINER
services:
  service_1_container:
    image: localhost:5002/healthy-image
    credentials:
      username: $DOCKER_USR_SERVICE_1_CONTAINER
      password: $DOCKER_PW_SERVICE_1_CONTAINER
    options: --health-cmd "stat /ready || exit 1" --health-interval 1s --health-timeout 3s --health-retries 3
  service_2_container:
    image: localhost:5003/healthy-image
    credentials:
      username: $DOCKER_USR_SERVICE_2_CONTAINER
      password: $DOCKER_PW_SERVICE_2_CONTAINER
    options: --health-cmd "stat /ready || exit 1" --health-interval 1s --health-timeout 3s --health-retries 3
workflows:
  docker-login-multiple-containers:
    before_run:
    - _start_mock_registry_for_step_execution_container
    - _start_mock_registry_for_service_1_container
    - _start_mock_registry_for_service_2_container
    after_run:
    - _cleanup_mock_registry_for_step_execution_container
    - _cleanup_mock_registry_for_service_1_container
    - _cleanup_mock_registry_for_service_2_container
    title: Expected to pass docker login
    steps:
    - with:
        container: step_execution_container
        services:
        - service_1_container
        - service_2_container
        steps:
        - script:
            title: Should pass
            inputs:
            - content: exit 0
  _start_mock_registry_for_step_execution_container:
    envs:
    - PORT: 5001
    - USR: $DOCKER_USR_STEP_EXECUTION_CONTAINER
    - PASS: $DOCKER_PW_STEP_EXECUTION_CONTAINER
    after_run:
    - _start_mock_registry
  _start_mock_registry_for_service_1_container:
    envs:
    - PORT: 5002
    - USR: $DOCKER_USR_SERVICE_1_CONTAINER
    - PASS: $DOCKER_PW_SERVICE_1_CONTAINER
    after_run:
    - _start_mock_registry
  _start_mock_registry_for_service_2_container:
    envs:
    - PORT: 5003
    - USR: $DOCKER_USR_SERVICE_2_CONTAINER
    - PASS: $DOCKER_PW_SERVICE_2_CONTAINER
    after_run:
    - _start_mock_registry
  _start_mock_registry:
    steps:
    - script:
        title: setup mock registry for step execution container
        inputs:
        - content: |-
            mkdir auth_$PORT
            docker run --entrypoint htpasswd httpd:2 -Bbn $USR $PASS > auth_$PORT/htpasswd
            docker pull --platform linux/amd64 registry:latest
            docker run -d -p $PORT:5000 --restart always --name registry_$PORT \
              -v "$(pwd)"/auth_$PORT:/auth_$PORT \
              -e "REGISTRY_AUTH=htpasswd" \
              -e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm" \
              -e REGISTRY_AUTH_HTPASSWD_PATH=/auth_$PORT/htpasswd \
              registry
            docker login localhost:$PORT -u $USR -p $PASS
            docker build -t healthy-image -f ${SRC_DIR_IN_GOPATH}/_tests/integration/docker_test.Dockerfile.healthy-container .
            docker tag healthy-image localhost:$PORT/healthy-image
            docker push localhost:$PORT/healthy-image
            docker logout localhost:$PORT
  _cleanup_mock_registry_for_step_execution_container:
    envs:
    - PORT: 5001
    after_run:
    - _cleanup_mock_registry
  _cleanup_mock_registry_for_service_1_container:
    envs:
    - PORT: 5002
    after_run:
    - _cleanup_mock_registry
  _cleanup_mock_registry_for_service_2_container:
    envs:
    - PORT: 5003
    after_run:
    - _cleanup_mock_registry
  _cleanup_mock_registry:
    steps:
    - script:
        is_always_run: true
        title: cleanup mock registry
        inputs:
        - content: |-
            docker stop registry_$PORT
            docker rm registry_$PORT
