envs:
- DOCKER_USR_STEP_EXECUTION_CONTAINER: test_usr_step_execution_container
- DOCKER_PW_STEP_EXECUTION_CONTAINER: test_pwd_step_execution_container
- DOCKER_USR_SERVICE_1_CONTAINER: test_usr_service_1_container
- DOCKER_PW_SERVICE_1_CONTAINER: test_pwd_service_1_container
- DOCKER_USR_SERVICE_2_CONTAINER: test_usr_service_2_container
- DOCKER_PW_SERVICE_2_CONTAINER: test_pwd_service_2_container
