//go:build steplib_e2e

package steplibe2e

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// reportPath picks where to write the report: the bitrise deploy dir when set
// (so the orchestrator collects it as a build artifact), else a temp file.
func reportPath() string {
	name := "steplib_log_parity_report.md"
	if d := os.Getenv("BITRISE_DEPLOY_DIR"); d != "" {
		return filepath.Join(d, name)
	}
	return filepath.Join(os.TempDir(), name)
}

// writeReport renders the per-cell comparisons and a roll-up into a markdown
// file and returns the path it wrote to.
func writeReport(comparisons []comparison, runStatus []string) (string, error) {
	var b strings.Builder
	b.WriteString("# Steplib v1 vs v2 activation — log parity report\n\n")
	b.WriteString("Generated by `integrationtests/steplibe2e`. Each step+version was activated\n")
	b.WriteString("through the legacy (v1) and API (v2) paths in JSON+debug log mode; the\n")
	b.WriteString("`bitrise_cli` log lines were normalized (durations, paths, hashes stripped)\n")
	b.WriteString("and diffed by (level, message).\n\n")

	b.WriteString("## Matrix run status\n\n")
	for _, s := range runStatus {
		b.WriteString("- " + s + "\n")
	}
	b.WriteString("\n")

	var v1OnlyGroups, v2OnlyGroups [][]logLine
	b.WriteString("## Per step+version divergences (v1-source vs each v2 variant)\n\n")
	for _, c := range comparisons {
		b.WriteString(fmt.Sprintf("### %s @ %s\n\n", c.step, displayRef(c.versionRef)))
		b.WriteString(fmt.Sprintf("- v1-source: %s\n", c.v1Status))
		for _, p := range c.pairs {
			b.WriteString(fmt.Sprintf("- %s: %s\n", p.v2Variant, p.v2Status))
		}
		b.WriteString("\n")
		for _, p := range c.pairs {
			v1OnlyGroups = append(v1OnlyGroups, p.v1Only)
			v2OnlyGroups = append(v2OnlyGroups, p.v2Only)
			b.WriteString(fmt.Sprintf("**v1-source vs %s**\n\n", p.v2Variant))
			if len(p.v1Only) == 0 && len(p.v2Only) == 0 {
				b.WriteString("_No log divergences._\n\n")
				continue
			}
			writeLines(&b, "Only in **v1-source**", p.v1Only)
			writeLines(&b, "Only in **"+p.v2Variant+"**", p.v2Only)
		}
	}

	b.WriteString("## Roll-up across the matrix\n\n")
	b.WriteString("### Logged by v1-source but missing from a v2 variant (parity gaps to consider filling)\n\n")
	writeTallies(&b, rollup(v1OnlyGroups))
	b.WriteString("### Logged by a v2 variant but missing from v1-source\n\n")
	writeTallies(&b, rollup(v2OnlyGroups))

	path := reportPath()
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

func displayRef(ref string) string {
	if ref == "" {
		return "latest"
	}
	return ref
}

func writeLines(b *strings.Builder, heading string, lines []logLine) {
	if len(lines) == 0 {
		return
	}
	b.WriteString(heading + ":\n\n")
	for _, l := range lines {
		b.WriteString(fmt.Sprintf("- `[%s]` %s\n", l.Level, l.Message))
	}
	b.WriteString("\n")
}

func writeTallies(b *strings.Builder, tallies []tally) {
	if len(tallies) == 0 {
		b.WriteString("_None._\n\n")
		return
	}
	for _, t := range tallies {
		b.WriteString(fmt.Sprintf("- (%dx) `[%s]` %s\n", t.count, t.line.Level, t.line.Message))
	}
	b.WriteString("\n")
}
